// let a = 420;
// a = 69;
// return a;

let a = 69;
if a < 20 {
    return a + 1;
} else {
    return a - 1;
}

// let n = 12;
// let n1 = 1;
// let n2 = 1;
// let i = 0;
// for i = 2; i < n; i = i + 1 {
//     let tmp = n1;
//     n1 = n2;
//     n2 = tmp + n2;
// }
// let res = (n1 + n2) / n;

// let a = 1 + 69 / 12 * (62 - 17);

// fn addone ciao come stai {
//     let a = 2;
//     let b = 3;
//     let c = a + b;
// }
